"""Clinical reasoning boundary for ISH-Anatomi.

This module deliberately refuses to invent a diagnosis. A diagnosis can only be
returned when a configured, validated model has supplied evidence and the case
passes the safety gates defined here.
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class AssessmentStatus(str, Enum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    READY_FOR_VALIDATED_MODEL = "READY_FOR_VALIDATED_MODEL"


@dataclass(frozen=True)
class ClinicalEvidence:
    source_id: str
    observation: str
    value: Any
    provenance: str
    confidence: float | None = None


@dataclass
class DiagnosticAssessment:
    status: AssessmentStatus
    findings: list[str] = field(default_factory=list)
    differential: list[str] = field(default_factory=list)
    evidence: list[ClinicalEvidence] = field(default_factory=list)
    explanation: str = ""


class DiagnosticEngine:
    """Safe adapter for a future clinically validated diagnostic model.

    No clinical diagnosis is generated by this class. It validates inputs and
    exposes a stable interface that a validated model can implement later.
    """

    def assess(self, *, symptoms: list[str], observations: list[ClinicalEvidence]) -> DiagnosticAssessment:
        if not symptoms and not observations:
            return DiagnosticAssessment(
                status=AssessmentStatus.INSUFFICIENT_DATA,
                explanation="No clinical evidence was supplied."
            )
        return DiagnosticAssessment(
            status=AssessmentStatus.NOT_CONFIGURED,
            findings=["Clinical diagnostic model is not configured."],
            evidence=observations,
            explanation=(
                "ISH-Anatomi will not infer or fabricate a diagnosis. "
                "Connect only a validated clinical model with documented "
                "intended use, validation evidence and regulatory controls."
            )
        )
