const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ishAnatomi', {
  appInfo: () => ipcRenderer.invoke('app:info'),
  compileIntent: (text) => ipcRenderer.invoke('ai:compile', text),
  visualAtlasMatch: (payload) => ipcRenderer.invoke('visual:atlas-match', payload),
  bluetoothSelect: (deviceId) => ipcRenderer.invoke('bluetooth:select', deviceId),
  bluetoothCancel: () => ipcRenderer.invoke('bluetooth:cancel'),
  bluetoothPairingResponse: (response) => ipcRenderer.invoke('bluetooth:pairing-response', response),
  studyCard: (text) => ipcRenderer.invoke('study:card', text),
  createQuiz: (count, seed) => ipcRenderer.invoke('study:quiz', count, seed),
  clinicalAssess: (payload) => ipcRenderer.invoke('clinical:assess', payload),
  executeViewerActions: (actions) => ipcRenderer.invoke('viewer:actions', actions),
  probeList: () => ipcRenderer.invoke('probe:list'),
  probeStatus: () => ipcRenderer.invoke('probe:status'),
  probeConnect: (id) => ipcRenderer.invoke('probe:connect', id),
  probeDisconnect: () => ipcRenderer.invoke('probe:disconnect'),
  probeStreamStatus: () => ipcRenderer.invoke('probe:stream-status'),
  liveStart: (session) => ipcRenderer.invoke('imaging:start', session),
  liveStop: () => ipcRenderer.invoke('imaging:stop'),
  liveFrame: (frame) => ipcRenderer.invoke('imaging:frame', frame),
  usbCameraStart: (deviceId, kind) => ipcRenderer.invoke('usb-camera:start', deviceId, kind),
  usbCameraStop: () => ipcRenderer.invoke('usb-camera:stop'),
  usbCameraFrame: (payload) => ipcRenderer.invoke('usb-camera:frame', payload),
  onUsbCameraResult: (handler) => ipcRenderer.on('usb-camera:result', (_event, payload) => handler(payload)),
  phoneCameraSearch: () => ipcRenderer.invoke('phone-camera:search'),
  phoneCameraStart: () => ipcRenderer.invoke('phone-camera:start'),
  phoneCameraStatus: () => ipcRenderer.invoke('phone-camera:status'),
  phoneCameraStop: () => ipcRenderer.invoke('phone-camera:stop'),
  setVirtualCamera: (enabled) => ipcRenderer.invoke('phone-camera:set-virtual', Boolean(enabled)),
  virtualCameraStatus: () => ipcRenderer.invoke('phone-camera:virtual-status'),
  onLiveResult: (handler) => ipcRenderer.on('imaging:result', (_event, result) => handler(result)),
  onViewerActions: (handler) => ipcRenderer.on('viewer:actions:apply', (_event, actions) => handler(actions)),
  onPhoneCameraInfo: (handler) => ipcRenderer.on('phone-camera:info', (_event, info) => handler(info)),
  onPhoneCameraStatus: (handler) => ipcRenderer.on('phone-camera:status-update', (_event, status) => handler(status)),
  onPhoneCameraFrame: (handler) => ipcRenderer.on('phone-camera:frame', (_event, payload) => handler(payload)),
  onPhoneCameraPose: (handler) => ipcRenderer.on('phone-camera:pose', (_event, pose) => handler(pose)),
  onBluetoothDevices: (handler) => ipcRenderer.on('bluetooth:devices', (_event, devices) => handler(devices)),
  onBluetoothDevicesEmpty: (handler) => ipcRenderer.on('bluetooth:devices-empty', (_event, info) => handler(info)),
  onBluetoothPairingRequest: (handler) => ipcRenderer.on('bluetooth:pairing-request', (_event, details) => handler(details))
});
